export type {
  AppTab,
  CommunicationActionHandler,
  CommunicationStatus,
  CommunicationType,
  DraftChangeHandler,
  DraftReport,
  ReportActionHandler,
  ReportPriority,
  ReportStatus,
  SafetyCommunication,
  SegnalatoreAppProps,
  SegnalatoreAppVariant,
  SegnalatoreReport,
  SegnalatoreRoleGroup,
  SubmitHandler,
} from "@/modules/segnalazioni/ui";
