export type {
  AppTab,
  CommunicationActionHandler,
  CommunicationStatus,
  CommunicationType,
  DraftChangeHandler,
  DraftReport,
  ReportActionHandler,
  ReportPriority,
  ReportStatus,
  SafetyCommunication,
  SegnalazioneCapabilitiesDto,
  SegnalazioneCommentDto,
  SegnalazioneTimelineItemDto,
  SegnalatoreAppProps,
  SegnalatoreAppVariant,
  SegnalatoreReport,
  SegnalatoreRoleGroup,
  SubmitHandler,
  TimelineEventType,
} from "@/modules/segnalazioni/ui";
